apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-config
  namespace: hlidskjalf
  labels:
    app: echo
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  ACOUSTICS__ENDPOINT: "acoustics.acoustics:10443"
  ACOUSTICS__PROTOCOL: "grpc"
